Added things

diff --git a/generator/generate b/generator/generate
--- a/generator/generate
+++ b/generator/generate
@@ -3,6 +3,15 @@ echo "[*] Starting Lartype server"
 python /usr/local/bin/_lartype/threadingserver.py &
 SERVER=$!
 echo "[*] Started with PID $SERVER"
-/usr/local/bin/_lartype/wkhtmltopdf -B 30mm -T 30mm -R 20mm -L 20mm --disable-smart-shrinking --header-html http://localhost:23416/lartype/header.html --footer-html http://localhost:23416/lartype/footer.html http://localhost:23416/lartype/lartype.html output.pdf 
+EXITCODE=1
+while [ $EXITCODE -ne 0 ]
+do
+    /usr/local/bin/_lartype/wkhtmltopdf -B 30mm -T 30mm -R 20mm -L 20mm --disable-smart-shrinking --header-html http://localhost:23416/lartype/header.html --footer-html http://localhost:23416/lartype/footer.html http://localhost:23416/lartype/lartype.html output.pdf
+    EXITCODE=$?
+    if [ $EXITCODE = 1 ]
+    then
+        echo "[*] Error, trying again (wait!)"
+    fi
+done
 kill $SERVER
 echo "[*] Done!"
