Commit por las dudas

diff --git a/generator/generate_full b/generator/generate_full
--- a/generator/generate_full
+++ b/generator/generate_full
@@ -2,7 +2,16 @@
 echo "[*] Starting Lartype server"
 python /usr/local/bin/_lartype/threadingserver.py &
 SERVER=$!
-#echo "[*] Go!"
-/usr/local/bin/_lartype/wkhtmltopdf -B 20mm -T 20mm -R 20mm -L 20mm --disable-smart-shrinking http://localhost:23416/lartype/lartype.html output.pdf 
+echo "[*] Started with PID $SERVER"
+EXITCODE=1
+while [ $EXITCODE -ne 0 ]
+do
+    /usr/local/bin/_lartype/wkhtmltopdf -B 20mm -T 20mm -R 20mm -L 20mm --disable-smart-shrinking http://localhost:23416/lartype/lartype.html output.pdf 
+    EXITCODE=$?
+    if [ $EXITCODE = 1 ]
+    then
+        echo "[*] Error, trying again (wait!)"
+    fi
+done
 kill $SERVER
 echo "[*] Done!"
